### ISSUE TITLE
I notice the source implements the specific use case of replacing music library contents

### ISSUE THREAD

**Issue by riotrah** [semjon00/free-mp3-download.net-downloader#1]
Curious as to why that is - what's your personal use case for that? Redownloading in higher quality?

**Comment by semjonsona** [comment]
That's right, I used this to re-download about 200 compositions from my music collection in higher quality (flac). It was some time ago, I am not even sure whether these scripts still work. It would be cool if somebody could verify that they work and/or fix/improve them - I would happily accept merge requests. Adapting the scripts for other use cases would be cool, too. Thanks for expressing interest!
